### ISSUE TITLE
Local Port Problem

### ISSUE THREAD

**Issue by ikbalkazanc** [SeyithanDilek/Movie-Manager#1]
Im already using 8080 port. How ı can chance 8080 port?

**Comment by SeyithanDilek** [comment]
You should write server.port=portname in application.properties

**Comment by ikbalkazanc** [comment]
Can you send file made as dockerize?

**Comment by SeyithanDilek** [comment]
I'll try to add it soon.

**Comment by ikbalkazanc** [comment]
I found how it's made from a source. Thanks
